### ISSUE TITLE
Howto connect

### ISSUE THREAD

**Issue by ovaris** [Harmon758/postgresql-action#4]
Hi, I was just wondering what hostname should I use to connect postgresql db in github envirnoment?

**Comment by elpapi42** [comment]
+1

**Comment by shirshak55** [comment]
it uses default port 5432 on localhost. You can change database by using keys below with:
```
          postgresql db: "bs_test"
```

**Comment by aruprakshit** [comment]
I have below job syntax:

```yml
name: Ruby

on: [push]

jobs:
  unit_tests:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: 'surveymaster_test'
      - name: Build and test with Rake
        if: success()
        working-directory: backend/ruby
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec ./spec

```

But it seems the postgresql connection is not found and my test fails.

```sh
An error occurred while loading ./spec/controllers/admin/sessions_controller_spec.rb.
Failure/Error: ActiveRecord::Migration.maintain_test_schema!

PG::ConnectionBad:
  could not connect to server: No such file or directory
  	Is the server running locally and accepting
  	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
# ./spec/rails_helper.rb:29:in `<top (required)>'
# ./spec/controllers/admin/sessions_controller_spec.rb:3:in `require'
# ./spec/controllers/admin/sessions_controller_spec.rb:3:in `<top (required)>'
```

**Comment by jay-snee** [comment]
@aruprakshit What does your connection string look like? I found I had to explicitly set a username/password in the job config when using a URL string:

*database.yml*
```
test:
  <<: *default
  url: postgres://test:password@localhost/test
```

*my_action.yml*
```
name: Run rspec tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Set up PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql user: test
        postgresql password: password
    - name: Set up Redis
      uses: zhulik/redis-action@1.1.0
    - name: Build app
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:setup RAILS_ENV=test
    - name: Run specs
      run: |
        bundle exec rspec
```
