### ISSUE TITLE
Wait until server is fully started

### ISSUE THREAD

**Issue by MarkKremer** [Harmon758/postgresql-action#7]
I had some trouble connecting to the database immediately after this action. This resulted in a "connection reset by peer" error. Adding a sleep action between the actions solved it. However, it would be better if the postgresql action could wait the appropriate amount of time itself by pinging itself or something similar.

I think this would also solve https://github.com/Harmon758/postgresql-action/issues/6 but I'm not sure so therefor this separate issue.

**Comment by ihorost** [comment]
@MarkKremer As a temporary solution, I've changed the CI steps sequence: DB Setup - install dependencies - a step that uses DB.

**Comment by pashagolub** [comment]
Guys, can you help me? I cannot make this to work. No way. I've tried a lot already and came with this, but no luck at all:

```
jobs:

  ubuntu-marketplace:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: '11'
        postgresql db: 'postgres'
        postgresql user: 'postgres'
    - name: Check Postgres running
      run: |
        sleep 1m
        psql -U postgres -d postgres -h localhost -c "SELECT version()"
```

Output:
```
Check Postgres running
1m 1s
##[error]Process completed with exit code 2.
Run sleep 1m
  sleep 1m
  psql -U postgres -d postgres -h localhost -c "SELECT version()"
  shell: /bin/bash -e {0}
psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
##[error]Process completed with exit code 2.
```

What've I missed, @MarkKremer, @ihorost?

**Comment by MarkKremer** [comment]
I don't see anything wrong with that. This is what I used to debug my problem:
```
    - name: Wait / Sleep
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '10s'
   
    - name: Collect Docker Logs
      uses: jwalton/gh-docker-logs@v1.0.0
   
    - name: Check running containers
      run: docker ps -a
```
(put it after the postgres action)
